spring:
  application:
    name: product-service
  profiles:
    active: localhost
  main:
    allow-bean-definition-overriding: true #bean çakışmasına yani overriding'e izin vermek
info:
  component: Product Service  #bilgi amaçlı



server:
  port: 9788  # port bilgisi eklenmezse default 8080 portundan kalkar
---

spring:
  profiles: localhost
  cloud:
    config:
      uri: http://localhost:8888
  jpa:
    hibernate:
      ddl-auto: update #otomatik şema eklemesi için. update seçerek şemanın güncellemesini sağlıyoruz
    database-platform: org.hibernate.dialect.PostgreSQLDialect  #database olarak postgresql kullanılacağı belirtildi
    properties:
      hibernate:
        default_schema: stock_management  #şemanın ismi
  datasource:
    url: "jdbc:postgresql://localhost:5432/stock-management"
    username: postgres
    password: password
